<a href="https://colab.research.google.com/github/karthika95/Data_inference/blob/main/label_inference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/karthika95/Data_inference/

Cloning into 'Data_inference'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 29 (delta 10), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (29/29), done.

In [ ]:
import pandas as pd

In [ ]:
#HDTB data label - confusion matrix
conf_mat=pd.read_csv("Data_inference/conf_mat.csv")

In [ ]:
# conf_mat

,Unnamed: 0,Labels,Test Support,Training_support,rsp,ras-neg,rh,k2,lwg__psp,rt,...,rad,rbmod__relc,nmod,lwg__vaux_cont,_,main,k7,ras-k4,rbmod,pof__inv
0,0,rsp,21,155,15,0,0,0,0,0,...,0,0,4,0,0,0,0,0,0,0
1,1,ras-neg,8,68,0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,rh,143,1280,0,0,124,5,0,2,...,0,0,0,0,0,0,1,0,0,0
3,3,k2,1926,14350,0,0,4,1515,1,3,...,0,0,6,0,0,1,6,0,0,0
4,4,lwg__psp,8143,63001,0,0,0,2,8123,0,...,0,0,0,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,70,main,1804,14089,0,0,0,1,0,2,...,0,0,0,0,0,1764,0,0,0,0
71,71,k7,1169,8690,0,0,0,1,1,0,...,0,0,2,0,0,1,948,0,0,0
72,72,ras-k4,0,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
73,73,rbmod,6,33,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,5,0
74,74,pof__inv,1,Not in training data,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.head(2)

,Unnamed: 0,DOC_NO,SENT_NO,ID,FORM,LEMMA,CATEGORY,POS,FEAT,HEAD,DEPREL,DEPS,MISC,HEAD_PRED,HEAD_DEPREL,DEPREL_PRED
0,0,test.dat_,1,1,इसके,यह,pn,PRP,cat-pn|gen-any|num-sg|pers-3|case-o|vib-0_अतिर...,13,vmod,_,_,13,vmod,vmod
1,1,test.dat_,1,2,अतिरिक्त,अतिरिक्त,psp,PSP,cat-psp|gen-|num-|pers-|case-|vib-|tam-|chunkI...,1,lwg__psp,_,_,1,lwg__psp,lwg__psp

In [ ]:
# conf_mat.to_csv('/Data_inference/conf_mat.csv')

#Label meanings

In [ ]:
meanings=pd.read_csv("Data_inference/label_meanings.csv")

In [ ]:
df=pd.read_csv("Data_inference/final_file1.csv")

In [ ]:
df_pred=pd.read_csv("Data_inference/result_file.csv")

In [ ]:
#check if test file and result file are consistent and add the prediction columns to the final_file 
df['HEAD_PRED']=" "
df['DEPREL_PRED']=" "
for i in range(len(df)):
  if df['SENT_NO'][i]== df_pred['SENT_NO'][i] and df['ID'][i]==df_pred['ID'][i] and (df['FORM'][i]== df_pred['FORM'][i] or pd.isnull(df['FORM'][i])) :
    df['HEAD_PRED'][i]=df_pred['HEAD'][i]
    df['DEPREL_PRED'][i]=df_pred['DEPREL'][i]
  else:
    print("There is a mismatch in the IDs of test and predicted data at index :")
    print(i)
    break

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [ ]:
# df.head(5)

,Unnamed: 0,DOC_NO,SENT_NO,ID,FORM,LEMMA,CATEGORY,POS,FEAT,HEAD,DEPREL,DEPS,MISC,HEAD_PRED,DEPREL_PRED
0,0,test.dat_,1,1,इसके,यह,pn,PRP,cat-pn|gen-any|num-sg|pers-3|case-o|vib-0_अतिर...,13,vmod,_,_,13,vmod
1,1,test.dat_,1,2,अतिरिक्त,अतिरिक्त,psp,PSP,cat-psp|gen-|num-|pers-|case-|vib-|tam-|chunkI...,1,lwg__psp,_,_,1,lwg__psp
2,2,test.dat_,1,3,गुग्गुल,गुग्गुल,n,NNPC,cat-n|gen-m|num-sg|pers-3|case-d|vib-0|tam-0|c...,4,pof__cn,_,_,4,pof__cn
3,3,test.dat_,1,4,कुंड,कुंड,n,NNP,cat-n|gen-m|num-sg|pers-3|case-d|vib-0|tam-0|c...,8,ccof,_,_,8,ccof
4,4,test.dat_,1,5,",",COMMA,punc,SYM,cat-punc|gen-|num-|pers-|case-|vib-|tam-|chunk...,4,rsym,_,_,4,rsym

In [ ]:
sent_df=pd.read_csv('Data_inference/test_sent.csv')

In [ ]:
sent_df['SENT_NO'] = pd.to_numeric(sent_df['SENT_NO'])

In [ ]:
#Adding a column for sentences to which the words belong to
df['sentence']= " "
for i in range(len(df)):
  df['sentence'][i]=sent_df.loc[sent_df['SENT_NO']==df['SENT_NO'][i], 'FORM'].item()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
# df.head(5)

,Unnamed: 0,DOC_NO,SENT_NO,ID,FORM,LEMMA,CATEGORY,POS,FEAT,HEAD,DEPREL,DEPS,MISC,HEAD_PRED,DEPREL_PRED,sentence
0,0,test.dat_,1,1,इसके,यह,pn,PRP,cat-pn|gen-any|num-sg|pers-3|case-o|vib-0_अतिर...,13,vmod,_,_,13,vmod,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश..."
1,1,test.dat_,1,2,अतिरिक्त,अतिरिक्त,psp,PSP,cat-psp|gen-|num-|pers-|case-|vib-|tam-|chunkI...,1,lwg__psp,_,_,1,lwg__psp,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश..."
2,2,test.dat_,1,3,गुग्गुल,गुग्गुल,n,NNPC,cat-n|gen-m|num-sg|pers-3|case-d|vib-0|tam-0|c...,4,pof__cn,_,_,4,pof__cn,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश..."
3,3,test.dat_,1,4,कुंड,कुंड,n,NNP,cat-n|gen-m|num-sg|pers-3|case-d|vib-0|tam-0|c...,8,ccof,_,_,8,ccof,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश..."
4,4,test.dat_,1,5,",",COMMA,punc,SYM,cat-punc|gen-|num-|pers-|case-|vib-|tam-|chunk...,4,rsym,_,_,4,rsym,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश..."

In [ ]:
path="/Data_inference/final_file.tsv"
train = pd.read_csv(path,sep='\t', encoding='utf-8')

In [ ]:
df.head()

In [ ]:
# meanings.head()

#Support

In [ ]:
def support(label1,label2):
  idx_l1=int(conf_mat[conf_mat['Labels']==label1].index.values)
  idx_l2=int(conf_mat[conf_mat['Labels']==label2].index.values)
  columns=['label','Train_support','Test_support']
  support=pd.DataFrame(columns=columns)
  support.loc[len(support.index)] = [label1, conf_mat['Training_support'][idx_l1], conf_mat['Test Support'][idx_l1]]
  support.loc[len(support.index)] = [label2, conf_mat['Training_support'][idx_l2], conf_mat['Test Support'][idx_l2]]
  print(support)

#Confusion Pair

In [ ]:
def info(count,idx,label1,label2):
  columns=['label_type','labels','Meaning_Sanskrit','Meaning_English']
  conf=pd.DataFrame(columns=columns)
  conf['label_type']=['annotated label', 'predicted label']
  conf['labels']=[label1,label2]
  def meaningS(i):
    return meanings.loc[meanings['Label'] == conf['labels'][i], 'Meaning(Sanskrit)'].iloc[0]
  def meaningE(i):
    return meanings.loc[meanings['Label'] == conf['labels'][i], 'Meaning(English)'].iloc[0]
  if label1 in meanings['Label'].values:
    if label2 in meanings['Label'].values:
      conf['Meaning_Sanskrit']= [meaningS(0),meaningS(1)]
      conf['Meaning_English']=[meaningE(0),meaningE(1)]
    else:
      conf['Meaning_English'][0]=meaningE(0)
      conf['Meaning_Sanskrit'][0]=meaningS(0)
  elif label2 in meanings['Label'].values:
    conf['Meaning_English'][1]=meaningE(1)
    conf['Meaning_Sanskrit'][1]=meaningS(1)
  print("Wrongly predicted sentence\n")
  print(df['sentence'][idx] + "\nword: "+ df['FORM'][idx] +"\thead: " + str(df['HEAD'][idx]) + "\tsent_id: " + str(df['ID'][idx]) + "\n")
  if(count==0):
    print(conf)
    print("\n")
    print(support(label1,label2))
    count+=1

    print("Examples of "+label1+"\n")
    c=1;
    
    #To print examples of each label from training data

    # for idx in range(len(train)):
    #   if train['karka Relation'][idx]==label1:
    #     print(train['sentence'][idx] + "\nword: "+ train['Inflection/Surface form'][idx] +"\thead: " + str(train['head_inflection'][idx]) + "\tsent_id: " + str(df['ID'][idx]) + "\n")
    #     c+=1
    #   if c>3:
    #     break       
    # print("Examples of "+str(label2)+"\n")
    # c=1;
    # for idx in range(len(train)):
    #   if train['karka Relation'][idx]==label2:
    #     print(train['sentence'][idx] + "\nword: "+ train['Inflection/Surface form'][idx] +"\thead: " + str(train['head_inflection'][idx]) + "\tsent_id: " + str(df['ID'][idx]) + "\n")
    #     c+=1
    #   if c>3:
    #     break  
  
  input("Press Enter for next example: ")

In [ ]:
# train.head()

In [ ]:
count=0
label1=input("Annotated label: ")
label2=input("Predicted label: ")
print("\n")
for idx in range(len(df)):
  if df['DEPREL'][idx]==label1 and df['DEPREL_PRED'][idx]==label2:
    info(count,idx,label1,label2)
    count+=1
if idx>=(len(df)-1):
  print("No more confustion pairs..")

Annotated label: k1
Predicted label: k2


Wrongly predicted sentence

देवी की प्रतिमा जिस स्थान पर रखी गई है उसी पवित्र स्थल के आसपास भक्त बैठे रहते हैं तथा आराधना करते हैं ।
word: प्रतिमा	head: 7	sent_id: 3

        label_type labels Meaning_Sanskrit     Meaning_English
0  annotated label     k1           kartaa  doer/agent/subject
1  predicted label     k2            karma      object/patient


  label Train_support Test_support
0    k1         19332         2302
1    k2         14350         1926
None
Examples of k1

Press Enter for next example:
Wrongly predicted sentence

भारत के सांस्कृतिक धार्मिक तीर्थ स्थलों में माँ काली का मंदिर सबसे प्राचीन माना जाता है ।
word: मंदिर	head: 14	sent_id: 11

KeyboardInterrupt: ignored